import 'server-only';
import { LmsProvider } from '@prisma/client';
import { logger } from '@/server/lib/logger';
import type {
  AdapterConfig,
  ExternalAnnouncement,
  ExternalAssignment,
  ExternalCalendarEvent,
  ExternalCourse,
  ExternalExam,
  ExternalFile,
  ExternalGrade,
  FetchOptions,
  LmsAdapter,
  LmsProfile,
  LmsRefreshResult,
  LmsTokens,
} from './types';
import { LmsProviderError } from './types';
import type { SyncMetrics } from './metrics';

/**
 * Moodle adapter — real implementation against the Moodle Web Services (REST)
 * API. Auth model is different from Canvas: Moodle uses per-user Web Services
 * tokens (generated by the student in their profile → Security keys). The
 * token IS the credential; there is no OAuth code exchange and no refresh.
 *
 *   GET  {portal}/webservice/rest/server.php
 *        ?wstoken={token}&wsfunction={fn}&moodlewsrestformat=json[&params]
 *
 * Errors: Moodle returns HTTP 200 even for API errors, with a body of the shape
 * `{ exception, errorcode, message }`. Every request goes through `call()`
 * which detects that shape and throws.
 *
 * All wsfunctions used here are available in Moodle 3.5+; the announcements
 * path uses `mod_forum_get_forum_discussions` on the site-level "News forum"
 * (which every Moodle course auto-creates).
 */

type MoodleQuery = Record<string, string | number | undefined>;

interface MoodleSiteInfo {
  sitename: string;
  username: string;
  firstname?: string;
  lastname?: string;
  fullname?: string;
  userid: number;
  useridnumber?: string;
  userpictureurl?: string;
  release?: string;
  functions?: { name: string }[];
}

interface MoodleCourse {
  id: number;
  shortname?: string;
  fullname: string;
  displayname?: string;
  idnumber?: string;
  visible?: number;
  startdate?: number;
  enddate?: number;
  timemodified?: number;
  format?: string;
}

interface MoodleAssignment {
  id: number;
  cmid?: number;
  course: number;
  name: string;
  intro?: string;
  duedate?: number;
  cutoffdate?: number;
  grade?: number;
  timemodified?: number;
}

interface MoodleQuiz {
  id: number;
  course: number;
  coursemodule?: number;
  name: string;
  intro?: string;
  timeopen?: number;
  timeclose?: number;
  timelimit?: number;
  timemodified?: number;
}

interface MoodleForum {
  id: number;
  course: number;
  type?: string;
  name?: string;
}

interface MoodleDiscussion {
  id: number;
  discussion: number;
  parent?: number;
  subject: string;
  message?: string;
  userfullname?: string;
  created?: number;
  timemodified?: number;
}

interface MoodleModuleContent {
  type: string;
  filename: string;
  filepath?: string;
  filesize?: number;
  fileurl?: string;
  mimetype?: string;
  timemodified?: number;
}

interface MoodleModule {
  id: number;
  name: string;
  modname: string;
  url?: string;
  contents?: MoodleModuleContent[];
}

interface MoodleSection {
  id: number;
  name: string;
  modules?: MoodleModule[];
}

interface MoodleGradeItem {
  id: number;
  itemname: string;
  gradeformatted?: string;
  gradedatesubmitted?: number;
  grademin?: number;
  grademax?: number;
  graderaw?: number | null;
  percentageformatted?: string;
  cmid?: number;
}

interface MoodleGradeReport {
  usergrades?: { gradeitems: MoodleGradeItem[] }[];
}

interface MoodleCalendarGroup {
  courseid: number;
  events?: {
    id: number;
    name: string;
    description?: string;
    timestart: number;
    timeduration?: number;
    location?: string;
    url?: string;
    eventtype?: string;
    modulename?: string;
  }[];
}

export class MoodleAdapter implements LmsAdapter {
  readonly provider = LmsProvider.MOODLE;
  readonly version = '1.0.0';
  private readonly cfg: AdapterConfig;
  private readonly metrics?: SyncMetrics;

  constructor(cfg: AdapterConfig, metrics?: SyncMetrics) {
    this.cfg = cfg;
    this.metrics = metrics;
  }

  // --- Auth ----------------------------------------------------------------

  /**
   * Moodle doesn't use OAuth2 for this integration — the student generates a
   * Web Services token in their Moodle profile and pastes it. Return the docs
   * URL as a "how to get a token" pointer so the UI can surface it if needed.
   */
  getAuthorizeUrl(_state: string): string {
    return `${this.cfg.portalUrl}/user/managetoken.php`;
  }

  /**
   * There is no code exchange with Moodle. The `code` parameter is treated as
   * the raw Web Services token, validated with core_webservice_get_site_info,
   * and returned unchanged. This lets the OAuth-shaped adapter interface still
   * work for token-based providers.
   */
  async authenticate(codeOrToken: string): Promise<LmsTokens> {
    const tokens: LmsTokens = { accessToken: codeOrToken };
    // Validate — throws if the token is bad or the URL isn't a Moodle site.
    await this.call<MoodleSiteInfo>(tokens, 'core_webservice_get_site_info');
    return tokens;
  }

  /** Moodle Web Services tokens don't refresh; return the same token unchanged. */
  async refresh(refreshToken: string): Promise<LmsRefreshResult> {
    return {
      tokens: { accessToken: refreshToken },
      rotated: false,
    };
  }

  /**
   * Moodle exposes core_user_delete_wstoken but only for admins. Best-effort:
   * we just clear our local copy. The student can revoke the token themselves
   * from Site → Preferences → Security keys.
   */
  async revoke(_tokens: LmsTokens): Promise<void> {
    /* no-op */
  }

  // --- Data fetchers -------------------------------------------------------

  async getProfile(tokens: LmsTokens): Promise<LmsProfile> {
    const info = await this.call<MoodleSiteInfo>(tokens, 'core_webservice_get_site_info');
    return {
      remoteUserId: String(info.userid),
      name: info.fullname ?? (`${info.firstname ?? ''} ${info.lastname ?? ''}`.trim() || info.username),
      studentId: info.useridnumber || undefined,
      avatarUrl: info.userpictureurl,
      raw: info as unknown as Record<string, unknown>,
    };
  }

  async getCourses(tokens: LmsTokens, _opts?: FetchOptions): Promise<ExternalCourse[]> {
    const info = await this.call<MoodleSiteInfo>(tokens, 'core_webservice_get_site_info');
    const courses = await this.call<MoodleCourse[]>(
      tokens,
      'core_enrol_get_users_courses',
      { userid: info.userid },
    );
    const now = Math.floor(Date.now() / 1000);
    return courses.map((c) => ({
      externalId: String(c.id),
      name: c.fullname,
      code: c.shortname ?? c.idnumber ?? undefined,
      term: undefined,
      instructor: undefined,
      active: c.visible !== 0 && (!c.enddate || c.enddate === 0 || c.enddate > now),
      remoteUpdatedAt: c.timemodified ? new Date(c.timemodified * 1000) : undefined,
    }));
  }

  async getAssignments(
    tokens: LmsTokens,
    courseExternalId: string,
    opts?: FetchOptions,
  ): Promise<ExternalAssignment[]> {
    const data = await this.call<{ courses?: { assignments?: MoodleAssignment[] }[] }>(
      tokens,
      'mod_assign_get_assignments',
      { 'courseids[0]': Number(courseExternalId) },
    );
    const items = data.courses?.[0]?.assignments ?? [];
    const since = opts?.since;
    return items
      .filter((a) => !since || (a.timemodified ? new Date(a.timemodified * 1000) >= since : true))
      .map((a) => ({
        externalId: String(a.id),
        courseExternalId,
        title: a.name,
        description: stripHtml(a.intro),
        dueAt: a.duedate ? new Date(a.duedate * 1000) : undefined,
        maxPoints: a.grade,
        type: 'assignment',
        url: a.cmid ? `${this.cfg.portalUrl}/mod/assign/view.php?id=${a.cmid}` : undefined,
        submitted: false, // Full submission state needs mod_assign_get_submission_status per assignment.
        remoteUpdatedAt: a.timemodified ? new Date(a.timemodified * 1000) : undefined,
      }));
  }

  async getExams(
    tokens: LmsTokens,
    courseExternalId: string,
    opts?: FetchOptions,
  ): Promise<ExternalExam[]> {
    const data = await this.call<{ quizzes?: MoodleQuiz[] }>(
      tokens,
      'mod_quiz_get_quizzes_by_courses',
      { 'courseids[0]': Number(courseExternalId) },
    );
    const items = data.quizzes ?? [];
    const since = opts?.since;
    return items
      .filter((q) => !since || (q.timemodified ? new Date(q.timemodified * 1000) >= since : true))
      .map((q) => ({
        externalId: String(q.id),
        courseExternalId,
        title: q.name,
        description: stripHtml(q.intro),
        scheduledAt: q.timeopen ? new Date(q.timeopen * 1000) : undefined,
        durationMinutes: q.timelimit ? Math.round(q.timelimit / 60) : undefined,
        location: undefined,
        url: q.coursemodule ? `${this.cfg.portalUrl}/mod/quiz/view.php?id=${q.coursemodule}` : undefined,
        remoteUpdatedAt: q.timemodified ? new Date(q.timemodified * 1000) : undefined,
      }));
  }

  async getAnnouncements(
    tokens: LmsTokens,
    courseExternalId: string,
    opts?: FetchOptions,
  ): Promise<ExternalAnnouncement[]> {
    // Announcements live in the auto-created News forum (type = "news").
    let forums: MoodleForum[];
    try {
      forums = await this.call<MoodleForum[]>(tokens, 'mod_forum_get_forums_by_courses', {
        'courseids[0]': Number(courseExternalId),
      });
    } catch (err) {
      logger.warn({ err, courseExternalId }, 'moodle: forums fetch failed');
      return [];
    }
    const newsForum = forums.find((f) => f.type === 'news') ?? forums[0];
    if (!newsForum) return [];

    const disc = await this.call<{ discussions?: MoodleDiscussion[] }>(
      tokens,
      'mod_forum_get_forum_discussions',
      { forumid: newsForum.id, sortby: 'timemodified', sortdirection: 'DESC' },
    );
    const items = disc.discussions ?? [];
    const since = opts?.since;
    return items
      .filter((d) => !since || (d.timemodified ? new Date(d.timemodified * 1000) >= since : true))
      .map((d) => ({
        externalId: String(d.discussion),
        courseExternalId,
        title: d.subject,
        body: stripHtml(d.message),
        author: d.userfullname,
        postedAt: d.created ? new Date(d.created * 1000) : undefined,
        url: `${this.cfg.portalUrl}/mod/forum/discuss.php?d=${d.discussion}`,
        remoteUpdatedAt: d.timemodified ? new Date(d.timemodified * 1000) : undefined,
      }));
  }

  async getGrades(
    tokens: LmsTokens,
    courseExternalId: string,
    _opts?: FetchOptions,
  ): Promise<ExternalGrade[]> {
    const info = await this.call<MoodleSiteInfo>(tokens, 'core_webservice_get_site_info');
    const data = await this.call<MoodleGradeReport>(
      tokens,
      'gradereport_user_get_grade_items',
      { courseid: Number(courseExternalId), userid: info.userid },
    );
    const items = data.usergrades?.[0]?.gradeitems ?? [];
    return items.map((gi) => {
      const percentage = parsePct(gi.percentageformatted);
      return {
        externalId: String(gi.id),
        courseExternalId,
        label: gi.itemname || 'Grade',
        score: gi.graderaw ?? undefined,
        maxScore: gi.grademax,
        percentage: percentage ?? (gi.graderaw != null && gi.grademax
          ? (gi.graderaw / gi.grademax) * 100
          : undefined),
        letterGrade: gi.gradeformatted,
        postedAt: gi.gradedatesubmitted ? new Date(gi.gradedatesubmitted * 1000) : undefined,
      };
    });
  }

  async getFiles(
    tokens: LmsTokens,
    courseExternalId: string,
    opts?: FetchOptions,
  ): Promise<ExternalFile[]> {
    const sections = await this.call<MoodleSection[]>(tokens, 'core_course_get_contents', {
      courseid: Number(courseExternalId),
    });
    const since = opts?.since;
    const files: ExternalFile[] = [];
    for (const section of sections) {
      for (const mod of section.modules ?? []) {
        for (const content of mod.contents ?? []) {
          if (content.type !== 'file' || !content.fileurl) continue;
          if (since && content.timemodified && new Date(content.timemodified * 1000) < since) continue;
          // Composite id ensures files with the same filename in different
          // modules stay distinct.
          const externalId = `mod-${mod.id}-${content.filename}`;
          files.push({
            externalId,
            courseExternalId,
            filename: content.filename,
            mimeType: content.mimetype,
            sizeBytes: content.filesize,
            // Moodle file URLs require the token appended for download.
            url: appendMoodleToken(content.fileurl, tokens.accessToken),
            remoteUpdatedAt: content.timemodified ? new Date(content.timemodified * 1000) : undefined,
          });
        }
      }
    }
    return files;
  }

  async getCalendar(
    tokens: LmsTokens,
    courseExternalId: string,
    opts?: FetchOptions,
  ): Promise<ExternalCalendarEvent[]> {
    const data = await this.call<{ groupedbycourse?: MoodleCalendarGroup[] }>(
      tokens,
      'core_calendar_get_action_events_by_courses',
      { 'courseids[0]': Number(courseExternalId) },
    );
    const group = data.groupedbycourse?.[0];
    if (!group?.events?.length) return [];
    const since = opts?.since;
    return group.events
      .filter((e) => !since || new Date(e.timestart * 1000) >= since)
      .map((e) => {
        const start = new Date(e.timestart * 1000);
        const end = e.timeduration && e.timeduration > 0
          ? new Date((e.timestart + e.timeduration) * 1000)
          : undefined;
        let type: ExternalCalendarEvent['type'] = 'other';
        const modName = (e.modulename ?? '').toLowerCase();
        const evtType = (e.eventtype ?? '').toLowerCase();
        if (modName === 'quiz' || /exam|midterm|final/.test(e.name.toLowerCase())) type = 'exam';
        else if (modName === 'assign' || evtType === 'due') type = 'deadline';
        else if (modName === 'lesson' || modName === 'scorm') type = 'lecture';
        else if (modName === 'workshop') type = 'lab';
        return {
          externalId: `event-${e.id}`,
          courseExternalId,
          title: e.name,
          description: stripHtml(e.description),
          startAt: start,
          endAt: end,
          location: e.location ?? undefined,
          type,
          url: e.url,
        };
      });
  }

  // --- Internals -----------------------------------------------------------

  /**
   * Single request path for every WS function. Handles Moodle's HTTP-200-with-
   * error-body convention, JSON parsing failures, and 429/5xx retries with
   * exponential backoff (3 in-adapter attempts).
   */
  private async call<T>(
    tokens: LmsTokens,
    wsfunction: string,
    params: MoodleQuery = {},
    attempt = 0,
  ): Promise<T> {
    const url = new URL(`${this.cfg.portalUrl}/webservice/rest/server.php`);
    url.searchParams.set('wstoken', tokens.accessToken);
    url.searchParams.set('wsfunction', wsfunction);
    url.searchParams.set('moodlewsrestformat', 'json');
    for (const [k, v] of Object.entries(params)) {
      if (v === undefined) continue;
      url.searchParams.set(k, String(v));
    }

    let res: Response;
    const started = Date.now();
    try {
      res = await fetch(url.toString(), { method: 'GET' });
    } catch (err) {
      if (this.metrics) this.metrics.recordRequest(Date.now() - started);
      throw new LmsProviderError(
        this.provider,
        `network error calling ${wsfunction}: ${err instanceof Error ? err.message : String(err)}`,
        undefined,
        true,
      );
    }
    if (this.metrics) this.metrics.recordRequest(Date.now() - started);

    if (res.status === 429 || res.status >= 500) {
      if (attempt < 3) {
        const wait = Math.min(2 ** attempt * 500, 4000);
        await new Promise((r) => setTimeout(r, wait));
        return this.call<T>(tokens, wsfunction, params, attempt + 1);
      }
      throw new LmsProviderError(
        this.provider,
        `HTTP ${res.status} after ${attempt} retries at ${wsfunction}`,
        res.status,
        true,
      );
    }

    if (!res.ok) {
      throw new LmsProviderError(
        this.provider,
        `HTTP ${res.status} calling ${wsfunction}`,
        res.status,
      );
    }

    let body: unknown;
    try {
      body = await res.json();
    } catch (err) {
      throw new LmsProviderError(
        this.provider,
        `${wsfunction} returned non-JSON body: ${err instanceof Error ? err.message : ''}`,
      );
    }

    // Moodle error convention — HTTP 200 with a JSON error object.
    if (body && typeof body === 'object' && 'exception' in body) {
      const err = body as { exception?: string; errorcode?: string; message?: string };
      const message = err.message ?? err.errorcode ?? 'unknown Moodle error';
      throw new LmsProviderError(
        this.provider,
        `${wsfunction} → ${err.exception ?? 'error'}: ${message}`,
      );
    }

    return body as T;
  }
}

/** Moodle file URLs need the token as a query param to serve the bytes. */
export function appendMoodleToken(fileUrl: string, token: string): string {
  const sep = fileUrl.includes('?') ? '&' : '?';
  return `${fileUrl}${sep}token=${encodeURIComponent(token)}`;
}

/** Best-effort HTML → text for Moodle intros/descriptions. Not a sanitiser. */
export function stripHtml(html?: string): string | undefined {
  if (!html) return undefined;
  return html
    .replace(/<br\s*\/?>(?=\S)/gi, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim() || undefined;
}

function parsePct(value?: string): number | undefined {
  if (!value) return undefined;
  const match = value.match(/([-\d.]+)/);
  if (!match) return undefined;
  const n = Number(match[1]);
  return Number.isFinite(n) ? n : undefined;
}
